In [6]:
import numpy as np

In [ ]:
# 创建0维的ndarray数组
array = np.array(5)
print(f"array的维度是:{array.ndim}")

array的维度是:0


In [8]:
arr = np.array([1,3,6])
print(arr)
print(arr.ndim)

[1 3 6]
1


In [11]:
arr = np.array([[1,4,67],[55,43,798]])
print(arr)
print(arr.ndim)

[[  1   4  67]
 [ 55  43 798]]
2


In [15]:
# numpy 数据都是同质性， 数据类型一致化，如果不一样会被强制转换
arr = np.array([2, "hello"])
print(arr.itemsize)

84


In [26]:
# 各种属性介绍
array = np.array([15,54.09,876])
array1 = np.array([["cpu","gpu","apu"],[23, 32, 43]])
print(f"数组形状:{array1.shape}")
print(f"元素个数有:{array1.size}")
print(f"元素的数据类型是:{array.dtype}")
print(f"元素转置:{array1.T}")
print(array1)

数组形状:(2, 3)
元素个数有:6
元素的数据类型是:float64
元素转置:[['cpu' '23']
 ['gpu' '32']
 ['apu' '43']]
[['cpu' 'gpu' 'apu']
 ['23' '32' '43']]


In [ ]:
# ndarray 的多种创建形式
arr = np.array([1,2,45])
